[profile.default]
src = 'contracts'
out = 'out'
libs = ['lib']
solc_version = '0.8.19'
optimizer = true
optimizer_runs = 200
via_ir = false
evm_version = 'paris'

[profile.ci]
fuzz_runs = 10_000
solc_version = '0.8.20'
optimizer = true
optimizer_runs = 200

[rpc_endpoints]
celo_mainnet = 'https://forno.celo.org'
alfajores = 'https://alfajores-forno.celo.org'

[etherscan]
celo_mainnet = { key = '${CELOSCAN_API_KEY}' }
alfajores = { key = '${CELOSCAN_API_KEY}' }